[openai] 
api_key = "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"
[google] 
api_key = "AIzaSyDd6clxZcueZXGGRySfubDm0NXAZyG1xVY"
[google2]
search_engine = "d5319dcfff9d64fb6"